IF EXISTS (SELECT name FROM sysobjects WHERE name = 'REGISTRAR_RETIRO_CAJERO' AND type = 'P')
    DROP PROCEDURE REGISTRAR_RETIRO_CAJERO
GO
CREATE PROCEDURE REGISTRAR_RETIRO_CAJERO
	@uNoCuenta varchar(5),
	@uMonto numeric(10,2)
AS
    BEGIN TRANSACTION CAJERO 
	INSERT INTO MOVIMIENTOS VALUES(@uNoCuenta,'A',GETDATE(),@uMonto);

	IF @@ERROR = 0 
		BEGIN
			UPDATE CLIENTES_BANCA SET Saldo = Saldo - @uMonto
			WHERE NoCuenta = @uNoCuenta 
			COMMIT TRANSACTION CAJERO 
		END
	ELSE 
		BEGIN 
			PRINT 'A transaction needs to be rolled back' 
			ROLLBACK TRANSACTION CAJERO 
		END 
GO

IF EXISTS (SELECT name FROM sysobjects WHERE name = 'REGISTRAR_DEPOSITO_VENTANILLA' AND type = 'P')
    DROP PROCEDURE REGISTRAR_DEPOSITO_VENTANILLA
GO
CREATE PROCEDURE REGISTRAR_DEPOSITO_VENTANILLA
	@uNoCuenta varchar(5),
	@uMonto numeric(10,2)
AS
    BEGIN TRANSACTION DEPOSITO 
	INSERT INTO MOVIMIENTOS VALUES(@uNoCuenta,'A',GETDATE(),@uMonto);

	IF @@ERROR = 0 
		BEGIN
			UPDATE CLIENTES_BANCA SET Saldo = Saldo + @uMonto
			WHERE NoCuenta = @uNoCuenta 
			COMMIT TRANSACTION DEPOSITO 
		END
	ELSE 
		BEGIN 
			PRINT 'A transaction needs to be rolled back' 
			ROLLBACK TRANSACTION DEPOSITO 
		END 
GO